# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_auto_20180328_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
